name: Manual workflow

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
      gender:
        description: 'Gender'
        type: choice
        options: 
          - male
          - female
      married:
        description: 'is married?'
        type: boolean

jobs: 
  manual:
    runs-on: ubuntu-latest

    steps: 
      - name: Greeting
        run: echo "${{ inputs.name }}"

      - name: Age
        run: echo ${{ inputs.age }}

      - name: Gender
        run: echo ${{inputs.gender}}
